### ISSUE TITLE
[skyine] app.scss 全局样式无法对 button 生效，建议文档说明

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#125]
例如设置以下代码，实际不生效
```
button {
  margin: 0!important;
}
```

**Comment by xiaweiss** [comment]
hack: 如果想在 app.wxss 里设置，又不想隔离组件。可以使用 ~ 语法
例如：app.wxss 设置
```css
.app-button {
    margin: 0!important;
}
```
自定义组件内：
```
<button class="~app-button" />
```
