### ISSUE TITLE
[skyline] picker-view 显示异常

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#126]
官方示例代码片段：https://developers.weixin.qq.com/s/imo08Qmg74JP

webview 模式，显示正常

![IMG_0260](https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/d410da32-8621-45d8-8ef5-c636f14f3847)

skyline 模式，显示异常

![IMG_0261](https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/ca889364-f895-47b7-bd5e-9e744f5067f9)

**Comment by xiaweiss** [comment]
试试把 picker 放大，把里面的 item 缩小

```css
.pickerview{
    width: 50%; height: 280rpx;transform:scale(2,2);transform-origin: 0 0;
}
.pickitemview{
    line-height: 26px;font-size: 10px;
}
```
