### ISSUE TITLE
[ios] scroll-view 在水平方向滚动时，滚动条丢失

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#213]
代码片段（官方示例）：https://developers.weixin.qq.com/s/QS63PSmM7SJq

安卓正常、ios skyline 模式正常

**Comment by xiaweiss** [comment]
hack：添加样式即可
```css
.wx-scroll-view {
  padding-bottom: 0 !important;
}
```
