### ISSUE TITLE
[skyline] animation 失效

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#325]
```css
.record-shadow {
  position: absolute;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  border-radius: 50%;
  animation: shadow 1.5s ease 0s infinite;
}

@keyframes shadow {
  0% {
    box-shadow: 0 0 0 30px rgb(204, 86, 86, 0.1);
  }
  100% {
    box-shadow: 0 0 0 130px rgb(204, 86, 86, 0);
  }
}
```
