### ISSUE TITLE
root-portal 在 webview 模式，无法继承全局 page 的样式

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#40]
代码片段：https://developers.weixin.qq.com/s/GOWTe0my7eJV

在 app.wxss 中设置了样式
```css
page {
    font-family: system-ui, -apple-system;
}
```
skyline 模式下，root-portal 里外文字相同
webview 模式下，root-portal 里外文字不同，见下图

![IMG_7468](https://user-images.githubusercontent.com/17960084/234231573-d512d072-57fb-47dc-8491-6db385846dcd.jpeg)
