### ISSUE TITLE
sticky-header 兼容 webview 模式

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#6]
组件文档：https://developers.weixin.qq.com/miniprogram/dev/component/sticky-header.html

sticky-header 仅 skyline 模式支持。在 webview 模式中，可以看作 view 来渲染，注意要加上 display: flex。

例如：
```html
<sticky-header class="sticky-header">
  <!-- 需要 sticky 定位的元素  -->
</sticky-header>
```

```css
.sticky-header {
  display: flex;
  position: sticky;
  left: 0;
  top: 0;
  flex-direction: column;
}
```

代码片段：https://developers.weixin.qq.com/s/bDW3hdmr73H8
